### ISSUE TITLE
The code for partitioning the datasets

### ISSUE THREAD

**Issue by slcheng97** [vlfom/rncdl#3]
Hi, thanks for your great work!
I'm curous about the data pre-process scripts for COCO annotations and VisualGenome annotations (e.g, how to get the COCO-half dataset). 
Could you share them with me? 
Thank you!

**Comment by vlfom** [comment]
Hi chengsilin,

Unfortunately, the code for splitting the datasets could be hard to find, so I'll first try to explain its logic here. The logic was very simple, - we tried to split COCO images randomly in half for a large number of iterations, and then picked such split that the number of COCO and LVIS annotations (object instances) per resulting image halves were roughly equal. As a result, we obtained two splits such that the difference of COCO annotations between them is ~40, and for LVIS annotations it's ~400.

Just yesterday we have revisited ReadME instructions and they include COCO-half json that we used in all experiments (and VisualGenome json as well).

Hope this helps, and please let me know if you have more questions.

**Comment by slcheng97** [comment]
I'm still condused with your statement:"such split that the number of COCO and LVIS annotations (object instances) per resulting image halves were roughly equal". Does it mean the number of images in COCO-half equals to those of another COCO-half? 
Anoher question is: why you try a large number of iterations for COCO split? Can I just try it only once?

**Comment by vlfom** [comment]
Yes, each half contains the same number of images (~50K). However, we also want to balance the number of annotations (both COCO and LVIS annotations, which we have access to) across the two halves. This problem does not have a simple analytical solution, so we use randomization. The idea is to try many random splits and choose the one that minimizes the difference in the number of annotations between the halves. The more random splits we try, the more likely we are to find a good split. Of course, you can try splitting only once, but this may result in a poor and skewed split in terms of number of annotations.

**Comment by slcheng97** [comment]
Thank you very much for your nice answer. 
Here, I have other questions about the dataset partition:
Does the number of annotations mean the number of bounding boxes in both two COCO-half? Can I keep the number of images in both COCO-half to be the same for eah class?

**Comment by vlfom** [comment]
Yes, the number of annotations means the number of bounding boxes in both
COCO-half. However, we do not enforce the number of images to be the same
for each class, because this would be too restrictive and may not be
possible for some rare classes. We only care about the overall number of
annotations, which reflects the diversity and richness of the data. At the
same time, we make sure that in each half, each class from COCO is represented
at least once. I suggest you read our paper carefully and check the files we provided,
where you can find the exact splits we used and the statistics of the
annotations. This will help you understand our method and reproduce our
results.

**Comment by slcheng97** [comment]
Thank you for sharing these details!
